spring.application.name=api-gateway
server.port=8090

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.instance-id=${spring.application.name}:${server.port}

#//iam-service
spring.cloud.gateway.routes[0].id=iam-service
spring.cloud.gateway.routes[0].uri=http://localhost:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/authentication/**,/api/v1/users/**
spring.cloud.gateway.routes[0].filters[0]=PreserveHostHeader

#//scheduling-service
spring.cloud.gateway.routes[1].id=scheduling-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/reservationsDetails

#//catalog-service
spring.cloud.gateway.routes[2].id=catalog-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/catalog

#//reviews-service
spring.cloud.gateway.routes[3].id=reviews-service
spring.cloud.gateway.routes[3].uri=http://localhost:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/reviews

#//payments-service
spring.cloud.gateway.routes[4].id=payments-service
spring.cloud.gateway.routes[4].uri=http://localhost:8085
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/payment-sources

# Global CORS configuration
# Global CORS configuration
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://34.31.160.85:4200,http://localhost:4200
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].exposedHeaders=Authorization,Content-Type
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true

# JWT configuration (shared secret with msvc-users)
authorization.jwt.secret=3b7f26e4c19a86d0f92b4c76aee1d9c07a83fd7a52f94d2e5b1e13ac59ef8b0a
authorization.jwt.issuer=iam-service
authorization.jwt.expiration.days=7

# Logging tuning
logging.level.org.springframework.cloud.gateway=INFO
logging.level.com.greatbuild.clearcost.msvc.apigateway=INFO